### ISSUE TITLE
Stop lying on GitHub

### ISSUE THREAD

**Issue by cpiotr** [moncefmechri/SimpleCPU#1]
The project name says `SimpleCPU`. It clearly is not simple.
Please, fix the name or simplify the project.

**Comment by moncefmechri** [comment]
CAN'T REPRODUCE, WON'T FIX

**Comment by cpiotr** [comment]
All caps, sophisticated. 
Thanks for your time, sir.

**Comment by mguby** [comment]
🤔🤔🤔
